#挂载目录需要提前创建并赋予权限,需要在/var/nginx/下把nginx配置文件写好.
version: '2.3'
services:
  log:
    image: nginx
    container_name: nginx
    restart: always
    dns_search: .
    volumes:
      - /var/nginx/nginx:/etc/nginx 
      - /var/nginx/html:/usr/share/nginx/html
    ports:
      - "8999:80"
      - "4443:443"
