version: '2.3'
services:
  log:
    image: registry.cn-hangzhou.aliyuncs.com/snuglove/jenkins:v1
    container_name: jenkins
    restart: always
    dns_search: .
    volumes:
      - /var/jenkins_home:/var/jenkins_home
    ports:
      - "50000:50000"
      - "8088:8080"
