#Spug 面向中小型企业设计的轻量级无 Agent 的自动化运维平台，整合了主机管理、主机批量执行、主机在线终端、文件在线上传下载、应用发布部署、在线任务计划、配置中心、监控、报警等一系列功能。
version: '2.3'
services:
  log:
    image: registry.aliyuncs.com/openspug/spug
    container_name: spug
    restart: always
    dns_search: .
    volumes:
      - /data:/data 
    ports:
      - "8999:80"

#初始化,设置登录账号和密码
#docker exec spug init_spug admin spug.dev

# 执行完毕后需要重启容器
# $ docker restart spug
