FROM centos:6.9
RUN curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo && \
        curl -o /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-6.repo  && \
         yum install unzip  mysql-server  php-pecl-zendopcache php-mysqli  nginx php-fpm php-gd php-mbstring  -y && \
         rm -rf  /etc/nginx/conf.d/*  && \
		 sed  -ri   's#user = .*#user = nginx#g'  /etc/php-fpm.d/www.conf  && \
         sed  -ri   's#group = .*#group = nginx#g'  /etc/php-fpm.d/www.conf && \
		 mkdir /code
ADD kedaoyun.conf /etc/nginx/conf.d/ 
ADD kodexplorer4.40.zip  /code
RUN unzip /code/kodexplorer4.40.zip  -d /code && \
        chown -R nginx:nginx /code  && \
        service mysqld start && \
        mysqladmin -uroot password '123456'
ADD kedaoyun.sh /kedaoyun.sh
CMD ["/bin/bash","/kedaoyun.sh"]
