FROM centos:6.9
RUN  curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo && \
          curl -o /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-6.repo  && \
          yum install unzip   mysql-server  php-pecl-zendopcache php-mysqli  nginx php-fpm php-gd -y  && \
          rm -rf /etc/nginx/conf.d/*  && \
          mkdir /code && \
          sed  -ri   's#user = .*#user = nginx#g'  /etc/php-fpm.d/www.conf  && \
          sed  -ri   's#group = .*#group = nginx#g'  /etc/php-fpm.d/www.conf 
ADD discuz.conf /etc/nginx/conf.d/ 
ADD discuz.zip  /code
RUN  unzip /code/discuz.zip  -d /code   && \
         mv /code/upload/*  /code       && \
         chown -R nginx:nginx /code    && \
          service mysqld start && \
          mysqladmin -uroot password '123456zc'
ADD discuz.sh /discuz.sh
CMD ["/bin/bash","/discuz.sh"]
